# Generated by Django 3.2.6 on 2023-11-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(max_length=255)),
                ('Product_Price', models.IntegerField(max_length=255)),
                ('Product_Detial', models.CharField(max_length=255)),
                ('Is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Token_Line',
            fields=[
                ('Token_id', models.AutoField(primary_key=True, serialize=False)),
                ('Token_Code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Img',
            fields=[
                ('Product_Img_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Img', models.ImageField(upload_to='reports/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebEcom.product')),
            ],
        ),
    ]
