# Generated by Django 3.2.6 on 2023-11-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebEcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Is_active',
            field=models.BooleanField(default=True),
        ),
    ]
